apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-app
spec:
  source:
    path: examples/helm/basic
    repoURL: https://github.com/ctablero/golfeado.git
    targetRevision: HEAD