apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: app-dev-observer
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    description: "Developer portal where end users can see and perform issue triage and also do on-demand syncs when needed"
    sourceRepos: 
    - '*'
    destinations:
    - namespace: 'default'
      server: 'https://kubernetes.default.svc'
    clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
    namespaceResourceWhitelist:
    - group: 'apps'
      kind: 'Deployment'
    - group: 'apps'
      kind: 'StatefulSet'
    - group: 'apps'
      kind: 'Service'
    roles:
    - name: readonly
      description: "Read only permissions to the project"
      policies:
      - p, proj:my-project:read-only, applications, get, my-project/*, allow
      groups:
      - my-oidc-group
