apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: core-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: apps
    repoURL: https://github.com/ctablero/bienmesabe.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
