apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: core-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://url-of-the-target-clusters-k8s-control-plane
  source:
    repoURL: https://url-of-the-repo-containing-child-apps